#include "/Engine/Private/Common.ush"
#include "/Engine/Private/ScreenPass.ush"

SCREEN_PASS_TEXTURE_VIEWPORT(Input)

FScreenTransform SvPositionToInputTextureUV;

Texture2D Input_Texture;
SamplerState Input_Sampler;

float4 MainPS(float4 SvPosition : SV_POSITION) : SV_Target0
{
	float2 InputUV = ApplyScreenTransform(SvPosition.xy, SvPositionToInputTextureUV);
	InputUV = clamp(InputUV, Input_UVViewportBilinearMin, Input_UVViewportBilinearMax);

	float4 Color = Input_Texture.SampleLevel(Input_Sampler, InputUV, 0);
	Color.rgb = 1.0 - Color.rgb;
	return Color;
}
